Install conf-python-3

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,6 +17,9 @@ jobs:
         run: |
           opam --version
           opam list
-          opam install -vv conf-cairo
+          opam install -vv conf-python-3
+          echo "print('hello!')" > test.py
+          python3 test.py || echo "python3 not found?"
+          python test.py || echo "python not found?"
 
 on: [push, workflow_dispatch]
